name: attomo
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.2
  - cupy
  - python=3.7
  - ipython
  - jupyter
  - jupyter_contrib_nbextensions
  - jupytext
  - matplotlib
  - numba  
  - numpy
  - pip
  - pylops
  - pyproj>=2.5.0
  - python-fastjsonschema
  - python-xxhash
  - scipy
  - tqdm
  - pip:
      - questionary
      - pyexodus>=0.1.3
      - mat73
